### ISSUE TITLE
Prüfung auf Aktualität der Angaben (Emailadresse)

### ISSUE THREAD

**Issue by henrixapp** [MaMpf-HD/mampf#100]
Wie soll das Verfahren zum überprüfen der Adressen ablaufen? Soll man einmal pro Semester  sich in Mampf zurückmelden o.ä.

**Comment by Splines** [comment]
Whenever a person has not logged in for 6 months, starting with #647 (release 1.14.0), you will receive a warning mail informing you that your MaMpf account will be deleted in 40 days if you don't log in again during that time.

With regards to emails: we still allow all kinds of emails to be used for MaMpf, not just Heidelberg University mails.
