### ISSUE TITLE
New exercise: Save button does not go away after pressing it

### ISSUE THREAD

**Issue by henrixapp** [MaMpf-HD/mampf#108]
If I edit a Media. After uploading a file the save button works, but does not hide, this confuses.

**Comment by fosterfarrell9** [comment]
I cannot reproduce this (neither in docker_development nor on our -dev server).  Could you be more specific? That rather looks like something went wrong with the upload. What does the browser console say?

**Comment by henrixapp** [comment]
I started with a fresh install of the db. After the first login I go to helpdesk, edit, create new media, Type: exercise, and upload a new manuscript. Then pressing the save button, but I dont get feedback. The console is empty.

**Comment by henrixapp** [comment]
Caused by `Policy.xml`. Maybe replacement of actual wrong lines needed.
