### ISSUE TITLE
Bootstrap icons?

### ISSUE THREAD

**Issue by henrixapp** [MaMpf-HD/mampf#110]
There are now official Bootstrap icons:
https://github.com/twbs/icons

In my perspective, we might migrate to those, because the fontawesome ones are too bold. (but that is my personal taste)

**Comment by fosterfarrell9** [comment]
To me, these Bootstrap icons look a little flimsy, I prefer the fontawesome icons. But that is my personal taste as well, maybe we should sample some opinions.
