### ISSUE TITLE
Persönliche Webseiten broken

### ISSUE THREAD

**Issue by christian-heusel** [MaMpf-HD/mampf#115]
Wenn ich als Dozent einer Veranstaltung eine persönliche Webseite angebe und dann auf "Testen" drücke, wird mir meine Seite und ein leerer Tab geöffnet. :computer: 

Zusätzlich wird die Webseite :globe_with_meridians: nicht auf meinem Dozentenprofil :bust_in_silhouette:  angezeigt:
![image](https://user-images.githubusercontent.com/26827864/96787621-5b514c00-13f2-11eb-949e-fab252a9e969.png)

**Comment by fosterfarrell9** [comment]
From my tests, the homepage is clickable.

**Comment by christian-heusel** [comment]
Ich habe das in 6fba3f6 noch so geändert, dass die Webseite gleich der Mailadresse angezeigt wird:
![image](https://user-images.githubusercontent.com/26827864/97083074-2c172680-160e-11eb-8af9-1ce618bef0f4.png)
