### ISSUE TITLE
Math not working in Mails

### ISSUE THREAD

**Issue by christian-heusel** [MaMpf-HD/mampf#118]
![image](https://user-images.githubusercontent.com/26827864/97120017-75519e00-1714-11eb-9dd6-010ae6ceb64f.png)

**Comment by christian-heusel** [comment]
Maybe we consider this a wontfix :blush:

**Comment by fosterfarrell9** [comment]
Unless you program a mail client that does understand js 😜. Of course, we could offer the editor a field with a fallback title without math, but that would be one more thing an editor had to fill out, so I would probably say just leave it as it is.

**Comment by christian-heusel** [comment]
Alright, now we have documented this as a design decision and can reference it when needed :blush:
