### ISSUE TITLE
Timeout on upload

### ISSUE THREAD

**Issue by christian-heusel** [MaMpf-HD/mampf#143]
Steps to reproduce:

1. Grab a large Video
2. Upload it as media
3. See shrine getting stuck on "Please Wait/Bitte warten"

This is probably due to a NginX configuration error.
https://stackoverflow.com/questions/24453388/nginx-reverse-proxy-causing-504-gateway-timeout/36589120#36589120

```
today at 09:37 nginx.1 | 2020/11/10 08:37:52 [warn] 99#99: *9761 upstream server temporarily disabled while reading response header from upstream, client: 192.168.144.1, server: localhost, request: "POST /videos/upload HTTP/1.1", upstream: "http://192.168.144.6:3000/videos/upload", host: "localhost:3009", referrer: "https://mampf.mathi.uni-heidelberg.de/media/16161/edit"
today at 09:37 nginx.1 | 2020/11/10 08:37:52 [error] 99#99: *9761 upstream timed out (110: Operation timed out) while reading response header from upstream, client: 192.168.144.1, server: localhost, request: "POST /videos/upload HTTP/1.1", upstream: "http://192.168.144.6:3000/videos/upload", host: "localhost:3009", referrer: "https://mampf.mathi.uni-heidelberg.de/media/16161/edit"
```

**Comment by fosterfarrell9** [comment]
Enlarging the RAM of the server has solved this problem (together with the optimizations of #155 and #166). Files of several GB can be uploaded without problems, so this issue can be considered closed for now.
