### ISSUE TITLE
Tagging by Students - Crowd Working

### ISSUE THREAD

**Issue by henrixapp** [MaMpf-HD/mampf#221]
Students know the best what tags they need and lecturers have not always the resources or time to tag all their videos.

Proposed is a system, where students can add tags to videos and review those made by others. Introducing a scoring system would help to identify misuse.
The tags  should be synced automatically, so that multiple users can tag at the same time. A display whether someone is typing can be very helpful in big lectures.

**Comment by Splines** [comment]
Thanks for your input. In my opinion, this won't work though. In reality, I bet that almost no student will want to tag lecture videos in their spare time. I also think that the creators of the video know best what it is about and what tags to assign.

I admit that even teachers often don't tag their own lectures and that they only use a fraction of the features that MaMpf offers. So we would have to motivate teachers / lecture editors to do this job (e.g. through UX improvements in existing menus). But IMHO, I don't think it's worth designing a feature to allow tagging by students instead. What do you think @fosterfarrell9?

**Comment by fosterfarrell9** [comment]
I agree  (and although this idea has been favored by myself for a long time, talks with several colleagues and students have convinced me that this is unlikely to work in practice).
