### ISSUE TITLE
API/client for Submissions

### ISSUE THREAD

**Issue by henrixapp** [MaMpf-HD/mampf#222]
For programming exercises the current setup is not efficient: students have to upload zip files and can not cooperate easily via mampf.

One idea is to provide a minimal git service to the users with some constraints (like file size limit etc, no branching in webinterface, protection for certain files after submission date). This service must be usable for normal users with no programming experience. This means that they can simply use the web interface.

Per lecture one student group would have one git repo and the foldernames per exercise are predefined. This means a student group would have to stick together over the whole duration of a course. This is usually the case in our courses.

```sh
exercise01/
   solution.pdf <-- by students, handed an via CLI or web interface
   review.pdf <-- created by tutor
```

For tutors it would be beneficiary to have a client that downloads and syncs reviews (to this git). The structure for a tutor would be:

```sh
exercise01/
   Alice_Bob_Charlie/
     solution.pdf
     review.pdf <-- created by tutor
  Diana_Elliot_Frank/
     solution.pdf
     review.pdf <-- created by tutor
```

Git compatibility would be great, because then no extra dependencies need to be installed. Maybe the git automatically includes a help file.

**Comment by henrixapp** [comment]
Probably easier would be to implement an ssh server and use scp for transmission.

**Comment by henrixapp** [comment]
As people are dropping out, teams should be able to change. This means that the interface manages the shared folders per submission and not per lecture.

**Comment by Splines** [comment]
I don't think this is a feasible feature for MaMpf. Users can upload their submissions as zip via the UI and then download the reviews by their tutors later on. Tutors can use the bulk download/upload feature to upload all corrections at once and let MaMpf automatically assign them to students.

I don't think adding another layer with a custom file server would be worth the effort. If users want to collaborate as team, I'd suggest them to create a GitHub repo on their own, e.g. to work with their partner on LaTeX files. In the end, they can just drag that PDF over to MaMpf and upload it there. Or, as in reality is often the case, users will work on their tablets with note apps and have their own cloud storage or use a feature of their OS to share files across devices.

In the end, you have to submit a finished document and I don't see the point of storing all the version history of that document in MaMpf directly, even for a programming exercise. If you really want to, you could also create a PDF with a link to your own GitHub repo where you've uploaded that document ;)

Do you agree, @fosterfarrell9?

---

> As people are dropping out, teams should be able to change. 

Maybe related: #645.
