### ISSUE TITLE
Remove (n+1)- queries

### ISSUE THREAD

**Issue by henrixapp** [MaMpf-HD/mampf#224]
We are currently having trouble with sorting them out.

**Comment by Splines** [comment]
A nice interview section by DHH regarding this can be found [here](https://www.youtube.com/watch?v=ktZLpjCanvg&t=267s). I don't think (n+1) queries are a problem for us, MaMpf is still really fast and we do cache a lot or rather Rails does it for us.

**Comment by Splines** [comment]
If you feel like it's a problem, please refer explicitly to lines of code in the MaMpf codebase.
