### ISSUE TITLE
Advanced User and Role Management 

### ISSUE THREAD

**Issue by henrixapp** [MaMpf-HD/mampf#241]
Currently the users and rights management is on a global scope (e.g. meaning an editor in one course can inspect all the others). It might be worth considering and implementing an ambitious rights management, that allows students to be tutors/editors in certain lectures.

**Comment by Splines** [comment]
There are no "inspect" actions anymore (or at least only remnants of it). We discussed this in the team meeting today and found that there is - meanwhile - a certain level of granularity, e.g. editors can be editors of courses, lectures or lessons with a full inheritance hierarchy of access privileges. Currently, #452 also deals with this, so I will close this issue for now.
