### ISSUE TITLE
Use `production=true` for yarn

### ISSUE THREAD

**Issue by christian-heusel** [MaMpf-HD/mampf#272]
I think webpacker and other dev-Deps would not not be installed, if this is `production=true`. We could move the devDeps in the package.json to dependencies and everything should work as expected.

_Originally posted by @henrixapp in https://github.com/MaMpf-HD/mampf/pull/271#discussion_r610360361_

**Comment by Splines** [comment]
We don't encounter any issues with that anymore in our current setup. And it's a good idea to have dev dependencies separated from the normal dependencies such that dev dependencies are not installed during the production build. This is the case right now, so I will close this issue.
