### ISSUE TITLE
Geogebra applets do not work anymore

### ISSUE THREAD

**Issue by fosterfarrell9** [MaMpf-HD/mampf#293]
It seems that the injection of gegebra applets as done in `app/assets/javascript/geogebra.coffee` has stopped working. There is a warning in the browser console:

`The resource ***/assets/geogebra_assets-**.js was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.`

**Comment by henrixapp** [comment]
Fixed in 0e6bf895efd92a71c87a7c8965ce657705daefc0
