### ISSUE TITLE
English Submission Invitation Email

### ISSUE THREAD

**Issue by LarsKue** [MaMpf-HD/mampf#297]
Submission invitation emails do not contain any content or links when sent in English.

It looks like this is (at least in part) due to incorrect naming in the `en.yml` locale file (currently under `mampf/config/locales/`). The item `submission_invitation` in `en.yml` is called `submission_invitation_html` in the German locale `de.yml`. More items differ in name, but I will not list them here.

My proposed (but untested) fix would be to rename the items in the English locale file to have the same names as in the German locale file.

Edit:

An affected email carries the tag `translation missing: en.mailer.submission_invitation_html [...]` instead of the link.

**Comment by henrixapp** [comment]
Thank you for reporting this issue. I have fixed the translation file.
