### ISSUE TITLE
Use Rewrite to provide "real" filename

### ISSUE THREAD

**Issue by henrixapp** [MaMpf-HD/mampf#305]
Because the filename provided via `/mediaforward` is a bit complex and not user friendly, we should create a rewrite rule and update the links, to reflect the filename to the user.

**Comment by tynsh** [comment]
I think we can also simplify this setup, since we now know how CORS works. I think we can simply change the CORS header for the media server and let the link point directly there.

**Comment by henrixapp** [comment]
Fixed in #317
