### ISSUE TITLE
Test mails via cypress

### ISSUE THREAD

**Issue by henrixapp** [MaMpf-HD/mampf#332]
MaMpf sends lots of mails and they can be tested via cypress:

https://www.cypress.io/blog/2021/05/11/testing-html-emails-using-cypress/#the-stmp-server-inside-cypress

**Comment by Splines** [comment]
Thanks, will keep this in mind when we create new Cypress tests that need this functionality! For now, we also test emails via RSpec directly, e.g. for the user cleaner in #647.
