### ISSUE TITLE
Multiple mails with same notification

### ISSUE THREAD

**Issue by 5cout** [MaMpf-HD/mampf#355]
When my tutor uploads a correction to one of our exercises, I receive multiple e-mails with the exact same notification. Last time, I received 5 mails, this time 11. Seems like a bug to me.

**Comment by fosterfarrell9** [comment]
Thank you for the report. Could you please contact us via the email adress specified on the page footer on all  MaMpf pages?
In the case of this bug, it would be good to have some more detailed information so we can look into the logs etc.

**Comment by 5cout** [comment]
Seems like it was a case of wrong execution by the tutor. Are you still interested in details?

**Comment by fosterfarrell9** [comment]
Yes, sure, maybe we can improve some things so that misexecutions can be prevented better in the future.
