### ISSUE TITLE
Prometheus exporter errors in production

### ISSUE THREAD

**Issue by tynsh** [MaMpf-HD/mampf#361]
Hey,

Does anybody know, why the following message pops up every 0.5 seconds in the logs?

`Prometheus Exporter, failed to send message Cannot assign requested address - connect(2) for "localhost" port 9394`

Best,

Tobias

**Comment by fosterfarrell9** [comment]
I think this should be fixed by #364.

**Comment by fosterfarrell9** [comment]
Fixed by #364.
