### ISSUE TITLE
Thyme-Player Resize Bug

### ISSUE THREAD

**Issue by Frodo161** [MaMpf-HD/mampf#405]
When pressing the iaButton (the button left of the fullscreen button), then resizing the window until the advanced control bar at the bottom is replaced by a simple control bar and back again, the side bar on the right bar opens again and covers the buttons on the right of the bottom bar. One can get access to the buttons again by clicking on the close icon of the right side bar.

**Comment by Splines** [comment]
I've checked and this is not an issue anymore. You've probably fixed this alongside the annotation tool in #533.
