### ISSUE TITLE
User cleaner does not detect all bounces correctly

### ISSUE THREAD

**Issue by fosterfarrell9** [MaMpf-HD/mampf#410]
The UserCleaner  worker which is run periodically to autodetect users who have mail adresses that are no longer valid does not detect many of the bounces.

**Comment by zebleck** [comment]
possibly solved through #414

**Comment by Splines** [comment]
### Some initial research

- > Your SMTP Envelope from address should not be the same as your RFC822 From Header address. Then any SMTP errors will go to the bounce address, but any real emails will go to the From address. Mailing List Managers use [VERP](https://en.wikipedia.org/wiki/Variable_envelope_return_path) to detect problems, by using a different envelope From address for each delivery. ~ [StackOverflow](https://stackoverflow.com/a/43783748/9655481)

- **Variable envelope return path (VERP)** ~ [Wikipedia](https://en.wikipedia.org/wiki/Variable_envelope_return_path)
We should probably use this with custom hashes such that no third-party person could just send an email to us with the recipient of another email in the header.

- Somehow differentiate between hard/soft bounces?
   - hard: address does not exist, feedback loop etc.
   - soft: mailbox quota etc

**Comment by Splines** [comment]
This shouldn't be a problem anymore with the reworked strategy of the user cleaner in #647.
