### ISSUE TITLE
Resizing Thyme player

### ISSUE THREAD

**Issue by Frodo161** [MaMpf-HD/mampf#423]
Currently, if one resizes the window, the Thyme player script only considers the window's width.
Thus, the native video screen won't be shown when resizing the window vertically. Moreover the normal screen shows up again when increasing the width of the video, although the screen is still to small for it.

**Comment by Splines** [comment]
That's not an issue anymore, the video player will we swapped with the native one even if you resize the window vertically. I think you fixed this with the annotation tool in #533.
