### ISSUE TITLE
Upgrade Cypress

### ISSUE THREAD

**Issue by christian-heusel** [MaMpf-HD/mampf#438]
The used cypress version is `7.6.0`, which is a few major versions behind the latest release [`12.8.1`](https://hub.docker.com/layers/cypress/included/12.8.1/images/sha256-5d6d7ee46c54debfdb0bbe8d304cdde6e2288fbd30e43d72193abdd30d967e59?context=explore):
 https://github.com/MaMpf-HD/mampf/blob/487ebca2a111e8a7e0c3e504b0dcfb50a9aa676d/docker/run_cypress_tests/Dockerfile_cypress#L1

This upgrade beyond version 10 requires some intervention:
```
There is a cypress.json file at the path: /
Cypress version 10.0.0 no longer supports cypress.json.
Please run cypress open to launch the migration tool to migrate to cypress.config.{js,ts,mjs,cjs}.
https://on.cypress.io/migration-guide
```

While one is at it the dependencies in [`spec/cypress/support`](https://github.com/MaMpf-HD/mampf/tree/main/spec/cypress/support) could also be updated 🔥

**Comment by Splines** [comment]
We now use an even newer version (v13) starting in #652.

> While one is at it the dependencies in [spec/cypress/support](https://github.com/MaMpf-HD/mampf/tree/main/spec/cypress/support) could also be updated 🔥

We entirely removed the [`cypress-on-rails`](https://github.com/shakacode/cypress-on-rails) dependency from our codebase. Instead, we use a custom API that is more similar to the FactoryBot API. Also see [this medium post](https://medium.com/p/3d25f19dc450/).

Also see the Wiki section [here](https://github.com/MaMpf-HD/mampf/wiki/Testing-%E2%9C%94#-cypress-frontend-tests) for how to run the frontend Cypress tests.
