### ISSUE TITLE
bootstrap 4.x EOL

### ISSUE THREAD

**Issue by christian-heusel** [MaMpf-HD/mampf#447]
> Bootstrap 4 will officially end of life January 1, 2023, though you’re obviously welcome to continue using it longer than that.

I noticed that the currently used bootstrap version is EOL since January, which is described in the following block post: https://blog.getbootstrap.com/2022/07/19/bootstrap-4-6-2/

I also noticed that it seems to be mixed whether bootstrap is used from the gems:

https://github.com/MaMpf-HD/mampf/blob/940a919ed6f2e5caa1decfbf1cc182e4f1988a86/Gemfile#L63-L65

or directly via the CloudFlare CDN:
https://github.com/MaMpf-HD/mampf/blob/eb8e57a50cce37869429d76fe178107425360d2f/app/views/layouts/edit_clicker.html.erb#L9

Information on the migration can be found here:
https://getbootstrap.com/docs/5.3/migration/

**Comment by Splines** [comment]
See also branch [`bootstrap5`](https://github.com/MaMpf-HD/mampf/tree/bootstrap5)

**Comment by christian-heusel** [comment]
> See also branch [`bootstrap5`](https://github.com/MaMpf-HD/mampf/tree/bootstrap5)

Linked it ✅

**Comment by Splines** [comment]
Hey @zebleck, could you please present to us the current state of the bootstrap migration (from 4 to 5)? Maybe you could open a new PR and add some details, so we know where we're at right now? Either you can finish the migration (what I would prefer ;)) or you tell us what points still need to be addressed and what you have done so far. Thanks 😊

**Comment by Splines** [comment]
Also see https://github.com/MaMpf-HD/mampf/issues/315

**Comment by zebleck** [comment]
Opened a pr https://github.com/MaMpf-HD/mampf/pull/463
