### ISSUE TITLE
Use semantic versioning (or part of it)

### ISSUE THREAD

**Issue by Splines** [MaMpf-HD/mampf#460]
[Semantic versioning](https://semver.org/) is a way to handle version numbers. In a nutshell: in `1.5.3`, 1 is the major version, 5 the minor version and 3 the patch:

> Given a version number MAJOR.MINOR.PATCH, increment the:
> 1. MAJOR version when you make incompatible API changes
> 2. MINOR version when you add functionality in a backwards compatible manner
> 3. PATCH version when you make backwards compatible bug fixes
Additional labels for pre-release and build metadata are available as extensions to the MAJOR.MINOR.PATCH format.

And from [here]():

> Today, SemVer is one of the world’s most well-known and heavily adopted versioning schemes. Several prominent package ecosystems (like Node’s npm and Rust’s Cargo) built-in SemVer’s concepts from day one. npm alone has more than 1.8 million packages, nearly all of which are [versioned with SemVer](https://docs.npmjs.com/about-semantic-versioning).

---

However, this is only for APIs where you have to watch out especially if you introduce breaking changes to users of your library/package, so you indicate this by an incremented major version. As we do not ship an API but rather a full platform on the web, semantic version technically does not apply to us. Still, I find the usage of the

- last number for patches useful to indicate for us internally that we just patched/hotfixed something
- middle number aka minor version useful to indicate that we introduced some new features or improved something
- major number for big updates (whatever that might be...)

In the end, versioning is not that important for us and no user will care what version MaMpf is right now. They care for what they can actually do with the product and if they experience a bug, they will always be at the latest version.

Any opinions on that? I plead for at least using patch numbers (so in this sense, the [latest release I've tagged](https://github.com/MaMpf-HD/mampf/releases/tag/1.4.4) should have really been `1.5.0` and now with the [bugfix](https://github.com/MaMpf-HD/mampf/pull/459) `1.5.1`).

**Comment by fosterfarrell9** [comment]
Sounds good to me. As an algebraist, having more structure is always preferable to me.

**Comment by Splines** [comment]
So from now on, we will at least use the last number for hotfixes/patches and the minor number for new features. Will close this issue.
