### ISSUE TITLE
Trix editor broken

### ISSUE THREAD

**Issue by fosterfarrell9** [MaMpf-HD/mampf#467]
The trix editor that we use in several instances seems broken. Bullet points are (sometimes) not displayed anymore, sometimes the content is only displayed correctly after page reload.

**Comment by Splines** [comment]
This is the problem:

E.g. for lecture 70 in mampf-dev, under organisational:
![image](https://user-images.githubusercontent.com/37160523/233631485-3bb04ed8-5dee-4029-9726-efab97669aa3.png)

However, this is the view that users get:
![image](https://user-images.githubusercontent.com/37160523/233631601-de097039-9f15-4fdb-8fca-b3bd326c18e0.png)

Bullet points are not working there.
