### ISSUE TITLE
Incorrect color for comment previews

### ISSUE THREAD

**Issue by fosterfarrell9** [MaMpf-HD/mampf#498]
It appears that #451 has introduced an unwanted side effect. Previews for comments are now colored yellow:

![wrong_color](https://github.com/MaMpf-HD/mampf/assets/28628554/4ae9380c-ee9f-4762-a7d8-f23bdb2276e3)

The reason seeems to be in these lines

```
.new-comment {
    color: #ffc107 !important;
}
```

It is possibly a name collision between our class - which is responsible for the coloring of the comment icon - and a css class provided by the commontator gem (I have not checked this, though).

**Comment by Splines** [comment]
Was no collision but instead - again - a scoping issue of the CSS class.

**Comment by fosterfarrell9** [comment]
What is strange is that in the commontator gem they make use of a `new-comment` css class, see e.g. this line 

```
<div id="commontator-thread-<%= thread.id %>-new-comment-link" class="new-comment">
```
in [here](https://github.com/lml/commontator/blob/main/app/views/commontator/threads/_reply.html.erb), but they do not define this class anywhere in their codebase. So, our global `new-omment` class rose to the occasion ;-).
