### ISSUE TITLE
Cancel button freezes parts of lecture edit page

### ISSUE THREAD

**Issue by Frodo161** [MaMpf-HD/mampf#514]
Go to the lecture edit page, scroll down and click on "Comments". Change something in this area such that the buttons "Save and exit" and "Cancel" appear. If one clicks "Cancel" the page does not reload (as it should) and some parts of the page freeze.

![Bildschirmfoto vom 2023-06-08 09-54-42](https://github.com/MaMpf-HD/mampf/assets/110454463/359e730f-5dd7-4649-a87a-efad4c77ef0d)

**Comment by fosterfarrell9** [comment]
I'll fix that after the Bootstrap 5 PR has been merged.
