### ISSUE TITLE
Migrate to Rails 7.1

### ISSUE THREAD

**Issue by fosterfarrell9** [MaMpf-HD/mampf#554]
Rails 7.1 has been released, so we should migrate at some point. See [here](https://edgeguides.rubyonrails.org/upgrading_ruby_on_rails.html#upgrading-from-rails-7-0-to-rails-7-1) for the migration guide.

**Comment by Splines** [comment]
If you cannot install `psych` with bundler, see [here](https://github.com/lewagon/rails-templates/issues/158)

**Comment by Splines** [comment]
```
[DEVISE] Please review the [changelog] and [upgrade guide] for more info on Hotwire / Turbo integration.

  [changelog] https://github.com/heartcombo/devise/blob/main/CHANGELOG.md
  [upgrade guide] https://github.com/heartcombo/devise/wiki/How-To:-Upgrade-to-Devise-4.9.0-%5BHotwire-Turbo-integration%5D
```

**Comment by Splines** [comment]
Fix for thredded: https://github.com/thredded/thredded/issues/979

**Comment by Splines** [comment]
## New cache format

The autogenerated `new_framework_defaults_7_1.rb` fails contains this comment:

```rb
###
# ** Please read carefully, this must be configured in config/application.rb **
#
# Change the format of the cache entry.
#
# Changing this default means that all new cache entries added to the cache
# will have a different format that is not supported by Rails 7.0
# applications.
#
# Only change this value after your application is fully deployed to Rails 7.1
# and you have no plans to rollback.
# When you're ready to change format, add this to `config/application.rb` (NOT
# this file):
#   config.active_support.cache_format_version = 7.1
```

We will do as stated there and only update the cache to the new format once we have Rails 7.1 running in production for at least a couple of weeks.

**Comment by Splines** [comment]
Deprecation `Passing the coder as positional argument`:

This was introduced [here in Rails](https://github.com/rails/rails/pull/47463). Their tests might help to figure out how to migrate, e.g. [this line](https://github.com/rails/rails/pull/47463/files#diff-57367a278d6a022551ac282c2487d10e79a44e24b4df88991a1925aa07f5b8deR52). Also related: [this PR](https://github.com/rails/rails/pull/47504) that addresses the deprecation warning in their own codebase.

- [`serialize` API in 7.0](https://api.rubyonrails.org/v7.0/classes/ActiveRecord/AttributeMethods/Serialization/ClassMethods.html#method-i-serialize)
- [`serialize` API in 7.1](https://api.rubyonrails.org/classes/ActiveRecord/AttributeMethods/Serialization/ClassMethods.html)
