### ISSUE TITLE
Windows line endings

### ISSUE THREAD

**Issue by christian-heusel** [MaMpf-HD/mampf#57]
Das einzige, was man unter Windows beachten muss, ist, dass man

`git config --global core.autocrlf false`

vor den Installationsaktivitäten mit Git und docker setzt. Das sollten wir wahrscheinlich noch in install.md als Hinweis reinsetzen (oder?). Wenn ich es richtig verstehe, ist die Empfehlung fürs Weiterarbeiten dann aber wieder ein

`git config --global core.autocrlf true
`
zu machen.

**Comment by fosterfarrell9** [comment]
Vielleicht können wir auch ein .gitattributes File anlegen und das dort reinschreiben, siehe [hier](https://docs.github.com/en/github/using-git/configuring-git-to-handle-line-endings). Ich werde das mal probieren.

**Comment by fosterfarrell9** [comment]
Mit dem `.gitattributes` file funktioniert es jetzt, egal welche Einstellung man unter Windows für `core.autocrlf` hat.

**Comment by fosterfarrell9** [comment]
Hm, vielleicht sollte es in den .gitattributes besser
`* text=auto eol=lf`
heißen?

**Comment by henrixapp** [comment]
`* text=auto eol=lf` bedeutet, dass alle Dateien als Text verstanden werden und automatisch der Zeilenumbruch angepasst wird. Ausnahmen müssen daher mit bspw. `*.png binary` gekennzeichnet werden. Dies war auch die Ursache für den Fehler https://github.com/MaMpf-HD/mampf/pull/81#pullrequestreview-493658768 , durch die Einstellung wurde dort eine Binärdatei beschädigt.

Die Einstellung ist somit richtig, nur das explizite Auflisten von Binärdateien muss man im Kopf behalten.
