### ISSUE TITLE
fix the test or fix the bugs

### ISSUE THREAD

**Issue by christian-heusel** [MaMpf-HD/mampf#66]
Since I neither really know how the tests work nor how MaMpf itself really functions someone else should take care of this.
We are striving to get a working CI configuration at the moment, but will not be done by getting this done since the tests currently either fail for no reason (which means the tests should be fixed) or there are some bugs which should be addressed in their issues.

**Comment by christian-heusel** [comment]
Is there any progress on this?

**Comment by Splines** [comment]
@christian-heusel #441 and #453 should close this, right?
