### ISSUE TITLE
Apache Solr potentially vulnerable to authentication bypass

### ISSUE THREAD

**Issue by christian-heusel** [MaMpf-HD/mampf#700]
FYI: 
- https://www.openwall.com/lists/oss-security/2024/10/15/9
- https://www.openwall.com/lists/oss-security/2024/10/15/8

I'm opening this as a public issue since my understanding is that these issues were responsibly disclosed 😊

**Comment by Splines** [comment]
Thanks for pointing this out. In the production dockerfile, we use `image: solr:8.11`. I have digged too long in the net to find some information about docker versioning. The way I understand it is that Docker performs no automatic minor-updates whatsoever, e.g. if we specify `8.11` it won't automatically update to a patch version `8.11.4`. The `8.11` is just a string that refers to a tag for docker.

However, for [solr on docker hub](https://hub.docker.com/_/solr/) the tags `8.11.4`, `8.11` and `8` all refer to the same Dockerfile [here](https://github.com/apache/solr-docker/blob/f11dfe66709370492d5b7b251d5eba5d70b8301d/8.11/Dockerfile) containing `ARG SOLR_VERSION="8.11.4"`. For me, this means that the images `8.11.4`, `8.11` and `8` were patched in hindsight.

Note that at MaMpf, we pull the images for every update, so even without something like [Watchtower](https://containrrr.dev/watchtower/) we should pull the new, patched solr-image automatically the next time we push a release.

To verify that we use the patched version, we should find out the exact image number. My idea would be to get the SHA-digest inside the running container and then check on the solr GitHub repo for that hash via the `docker inspect` command like described [here](https://stackoverflow.com/a/77082916/). Or do you know by chance a simpler solution? I couldn't find the "digest ..." line in our logs.

**Comment by Splines** [comment]
So finally, I've digged deeper to find out how to update the container in our infrastructure and successfully updated to version `8.11.4`. Sorry for the long delay and thanks for raising awareness of this issue.

**Comment by Splines** [comment]
Thanks again for having created the issue! Note that we've recently updated our [Security Policy](https://github.com/MaMpf-HD/mampf/security) such that you can write us privately in the future should you find more vulnerabilities. This is our preferred way even if CVEs might have been disclosed responsibly.
