### ISSUE TITLE
Firefox complains about cookie same site attribute

### ISSUE THREAD

**Issue by fosterfarrell9** [MaMpf-HD/mampf#77]
Apparently, there is a problem with our cookies and their same site attribute. In the future, these cookies will be declined.

**Comment by fosterfarrell9** [comment]
I alreay tried [this](https://github.com/rails/rails/pull/28297#issuecomment-682839723) and [this gem](https://github.com/pschinis/rails_same_site_cookie) to fix the issue, but none of them worked.

**Comment by henrixapp** [comment]
Adding an initializer `config/initializers/session_store.rb`with the following content:
```ruby
Rails.application.config.session_store :cookie_store, key: '_mampf_session', same_site: :strict
```
Fixes the issue for the (most important) session cookie. For  the other cookies I would suggest adding a "helper" in `application_controller.rb`:

```ruby
  def strict_cookie(val)
    {
        value: val,
        same_site: "Strict"
    }
  end
```
and calling it like this:

```ruby
cookies[:locale] = strict_cookie(I18n.locale)
```
instead of

```ruby
cookies[:locale] = I18n.locale
```
