### ISSUE TITLE
Linter config file

### ISSUE THREAD

**Issue by henrixapp** [MaMpf-HD/mampf#83]
Add a linter config file, so that developers see, to which coding styles we try to live up to.

**Comment by fosterfarrell9** [comment]
I would suggest using Rails' `.rubocop.yml` (maybe with some raised value for cyclotomic complexity, number of lines per model and similar values), ActionView's `coffeelint.json`, the `erb-lint`gem for `.erb` files with more ore less default settings (except with activated RuboCop checks on Ruby statements).  Thoughts or comments on that?
We would also need a config for `.js` files.
