### ISSUE TITLE
Transfer ownership to mampf-hd

### ISSUE THREAD

**Issue by henrixapp** [MaMpf-HD/mampf#95]
Move this project and migrate its web hooks to https://github.com/MaMpf-HD.

**Comment by christian-heusel** [comment]
I cannot do this since I am not able to see the settings with my current access level on this repo... 
Maybe @fosterfarrell9 can just send me a screenshot or summary of the hook settings privately?

**Comment by henrixapp** [comment]
We are waiting for @tynsh work today and will then initiate the transfer. @fosterfarrell9 will contact you.

**Comment by tynsh** [comment]
So I'm awake and will grab something to eat and will start to work afterwards. I've just joined the new mampf-hd Github group, so feel free to move the project.

**Comment by tynsh** [comment]
I'm here now. But for now I'll work on the deployment issues on mampf-dev and experimental
