### ISSUE TITLE
Livestreaming

### ISSUE THREAD

**Issue by henrixapp** [MaMpf-HD/mampf#99]
Es wäre toll, wenn es möglich wäre,  Vorlesungen live zu übertragen.

Dabei sollte es für einen Assistenten/StudentIn möglich sein, möglichst live die Videos zu taggen.

Neben den technischen Voraussetzungen sollte man auch juristische Bedingungen vorher klären, da es sich ja in gewisserweise um eine wiederkehrende Sendung mit signifikanter Zuschauerzahl handelt (Rundfunkstaatsvertrag).

Dieses Issue ist nur als Idee zu verstehen und nicht dringend.

---
It would be great if lectures could be broadcasted.

While streaming assistants or students should be able to livetag (#221).

Beside technical prerequisites one should ask some lawyer for  advice, whether the number of students is significant and therefore be subject to the *Rundfunkstaatsvertrag*.

This issue is not pressing and only an idea.

**Comment by henrixapp** [comment]
A good starting point might be https://github.com/GRVYDEV/Project-Lightspeed

**Comment by Splines** [comment]
While this generally sounds like a cool idea, I don't think that this is feasible within the scope of MaMpf (it's just too big of a feature) and probably not something that we really want for MaMpf. What do you think @fosterfarrell9?

**Comment by fosterfarrell9** [comment]
I think as well that this is not feasible in MaMpf.
